net:
  architecture:
    arch: conv
    conv:
      dilation: 1
      filter_shape: !!python/tuple
      - 7
      - 7
      num_bins: 2
      num_channels: 8
      num_layers: 30
    references_resnet:
      num_res_filters: 10
      shared_weights: true
  data:
    conv_features: []
    k: 10
    log_pssm: true
    resnet_features: []
train:
  batch_size: 1
  epochs: 20
  eval_dataset: eval
  in_train:
    save_checkpoints_steps: 2500
    save_summary_steps: 500
  opt:
    lr: 0.0001
  path: /Users/omerronen/Documents/MSA-Completion/models/template
  test_dataset: pfam
  train_dataset: train
