net:
  architecture:
    arch: ms_ss_ccmpred_pssm
    conv:
      dilation: 1
      filter_shape: !!python/tuple
      - 7
      - 7
      num_bins: 2
      num_channels: 7
      num_layers: 10
    references_resnet:
      num_res_filters: 10
      shared_weights: true
  data:
    conv_features: []
    k: 9
    resnet_features: []
train:
  batch_size: 1
  epochs: 30
  eval_dataset: eval
  in_train:
    save_checkpoints_steps: 2500
    save_summary_steps: 500
  opt:
    lr: 0.0001
  path: /cs/zbio/orzuk/projects/ContactMaps/src/Periscope/models/ccmpred_ss_pssm
  test_dataset: pfam
  train_dataset: train
