net:
  architecture:
    arch: periscope2
    conv:
      dilation: 1
      filter_shape: !!python/tuple
      - 7
      - 7
      num_bins: 10
      num_channels: 10
      num_layers: 10
    references_resnet:
      num_res_filters: 10
      shared_weights: true
  data:
    conv_features: []
    k: 10
    resnet_features: []
train:
  batch_size: 1
  epochs: 30
  eval_dataset: eval
  require_template: False
  in_train:
    save_checkpoints_steps: 2500
    save_summary_steps: 500
  opt:
    lr: 0.0002
  path: /vol/sci/bio/data/or.zuk/projects/ContactMaps/src/Periscope/models/prscope_bins_no_templates
  test_dataset: pfam
  train_dataset: train
